### model
model_name_or_path: /home/xiarui/.cache/modelscope/hub/models/HuggingFaceTB/SmolVLM-256M-Instruct/
image_max_pixels: 1048576 # 512 * 512 = 262144; 1024 * 1024 = 1048576 
video_max_pixels: 16384
trust_remote_code: true 

# /home/xiarui/.cache/modelscope/hub/models/HuggingFaceTB/SmolVLM-256M-Instruct/preprocessor_config.json
# 下面的size.longest_edge指如果开启resize，则resize后的图片尺寸为size.longest_edge * size.longest_edge（对于所有图片都是一样的）
# 这样会缺少对原始图片大小的感知，需要关闭do_resize
# max_image_size指patch后的大小，对所有图片都一样

### method
stage: sft
do_train: true
finetuning_type: full
freeze_vision_tower: true
freeze_multi_modal_projector: true
freeze_language_model: false
# deepspeed: examples/deepspeed/ds_z0_config.json

### dataset
dataset_dir: /home/xiarui/projects/AIPhoto/Dataset/final_train
dataset: photo_sft_training_data_person_en_resize_1024,photo_sft_training_data_person2_en_resize_1024
template: smolvlm
cutoff_len: 1000 #2048  # 通过sh/status_dataset_len.sh统计
# max_samples: 1000
overwrite_cache: true
preprocessing_num_workers: 16 
dataloader_num_workers: 4 

### output
output_dir: saves/smolvlm_256m_instruct_full_sft_20251131_gbs16_lr1e-4_ep20
logging_steps: 2
save_steps: 200
plot_loss: true
overwrite_output_dir: true
save_only_model: false
report_to: none  # choices: [none, wandb, tensorboard, swanlab, mlflow]

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 16
learning_rate: 1.0e-4
num_train_epochs: 20
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000
resume_from_checkpoint: null

### eval
# val_size: 0.1
# per_device_eval_batch_size: 1
# eval_strategy: steps
# eval_steps: 500
